version: "3"
services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000